//Codigo de J Query 
$(document).ready(function(){

	$("#bt1").click(function(){
		$("#div1").fadeToggle();
	})
	$("#bt2").click(function(){
		$("#div2").fadeToggle();
	})
	$("#bt3").click(function(){
		$("#div3").fadeToggle();
	})
	$("#bt4").click(function(){
		$("#div4").fadeToggle();
	})
	$("#bt5").click(function(){
		$("#div5").fadeToggle();
	})
	$("#bt6").click(function(){
		$("#div6").fadeToggle();
	})
	$("#bt7").click(function(){
		$("#div7").fadeToggle();
	})
	$("#bt8").click(function(){
		$("#div8").fadeToggle();
	})
	$("#bt9").click(function(){
		$("#div9").fadeToggle();
	})
	$("#bt10").click(function(){
		$("#div10").fadeToggle();
	})
	$("#bt11").click(function(){
		$("#div11").fadeToggle();
	})
	$("#bt12").click(function(){
		$("#div12").fadeToggle();
	})
	$("#bt13").click(function(){
		$("#div13").fadeToggle();
	})
	$("#bt14").click(function(){
		$("#div14").fadeToggle();
	})
	$("#bt5").click(function(){
		$("#divv").fadeToggle();
	})
})